version: '3.9'

services:
  # MongoDB
  mongodb:
    image: mongo:5.0
    container_name: app_mongodb
    ports:
      - '27017:27017'
    networks:
      - app
    volumes:
      - mongodb:/data/db

  # PostgresSQL
  postgres:
    image: postgres:13.4
    container_name: app_postgres
    ports:
      - '5432:5432'
    networks:
      - app
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  mongodb:
    name: app_mongodb
  postgres:
    name: app_postgres

networks:
  app:
    name: app_network
