name: Build App
on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head
        uses: nrwl/nx-set-shas@v3

      - name: Pre Build
        run: node scripts/pre-build.mjs >> $GITHUB_ENV

      - name: Build
        run: echo "${{ env.APPS_TO_BUILD }}"
