name: Build App
on:
  push:
    branches: ['*']

jobs:
  pre-build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    outputs:
      apps-to-build: ${{ steps.main.outputs.output }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head
        uses: nrwl/nx-set-shas@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install -w

      - id: main
        name: Pre Build
        run: node scripts/pre-build.mjs >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        app: ${{ fromJSON(needs.pre-build.outputs.apps-to-build) }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Build App
        run: pnpm run build:${{ matrix.app }}
