name: Build App
on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Derive appropriate SHAs for base and head for `nx affected` commands
      #   uses: nrwl/nx-set-shas@v3
      # - run: |
      #     echo "BASE: ${{ env.NX_BASE }}"
      #     echo "HEAD: ${{ env.NX_HEAD }}"

      # - name: Build
      #   run: git diff --name-only ${{ env.NX_BASE }} ${{ env.NX_HEAD }}
